CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
  name TEXT NOT NULL DEFAULT 'Admin', password_hash TEXT NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE roles (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE permissions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE user_roles (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY (user_id,role_id));
CREATE TABLE role_permissions (role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY (role_id,permission_id));
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL CHECK (btrim(name)<>''), phone TEXT,
  total_loan NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_loan>=0), old_loan NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (old_loan>=0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE stock_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, grams NUMERIC(14,3) NOT NULL CHECK (grams>0),
  price_per_gram NUMERIC(14,2) NOT NULL CHECK (price_per_gram>=0), remaining_grams NUMERIC(14,3) NOT NULL CHECK (remaining_grams>=0 AND remaining_grams<=grams),
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','CLOSED')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  grams_sold NUMERIC(14,3) NOT NULL CHECK (grams_sold>0), gross_amount NUMERIC(14,2) NOT NULL CHECK (gross_amount>=0),
  discount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount>=0 AND discount<=gross_amount), final_amount NUMERIC(14,2) NOT NULL CHECK (final_amount>=0),
  amount_received NUMERIC(14,2) NOT NULL CHECK (amount_received>=0 AND amount_received<=final_amount), balance NUMERIC(14,2) NOT NULL CHECK (balance>=0), comments TEXT,
  status TEXT NOT NULL DEFAULT 'POSTED' CHECK (status IN ('POSTED','REVERSED')), reversed_at TIMESTAMPTZ, reversed_by BIGINT REFERENCES users(id),
  created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (final_amount=gross_amount-discount), CHECK (balance=final_amount-amount_received)
);
CREATE TABLE sale_batch_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE RESTRICT,
  batch_id BIGINT NOT NULL REFERENCES stock_batches(id) ON DELETE RESTRICT, grams_deducted NUMERIC(14,3) NOT NULL CHECK (grams_deducted>0),
  unit_cost NUMERIC(14,2) NOT NULL CHECK (unit_cost>=0), UNIQUE (sale_id,batch_id)
);
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  amount NUMERIC(14,2) NOT NULL CHECK (amount>0), created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE settings (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id=1), rate_per_gram NUMERIC(14,2) NOT NULL DEFAULT 1000 CHECK (rate_per_gram>=0),
  special_025_030 NUMERIC(14,2) NOT NULL DEFAULT 250 CHECK (special_025_030>=0), special_050_060 NUMERIC(14,2) NOT NULL DEFAULT 500 CHECK (special_050_060>=0), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_code TEXT NOT NULL UNIQUE, account_name TEXT NOT NULL UNIQUE,
  account_type TEXT NOT NULL CHECK (account_type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')),
  parent_account_id BIGINT REFERENCES accounts(id) ON DELETE RESTRICT, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE SEQUENCE journal_entry_number_seq START 1;
CREATE TABLE journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entry_number TEXT NOT NULL UNIQUE, transaction_type TEXT NOT NULL,
  reference_type TEXT NOT NULL, reference_id TEXT NOT NULL, description TEXT NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  reversal_of_id BIGINT REFERENCES journal_entries(id) ON DELETE RESTRICT, posted_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE journal_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, journal_entry_id BIGINT NOT NULL REFERENCES journal_entries(id) ON DELETE RESTRICT,
  account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT, debit NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (debit>=0),
  credit NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (credit>=0), description TEXT,
  CHECK ((debit>0 AND credit=0) OR (credit>0 AND debit=0))
);
CREATE TABLE audit_logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL,
  entity_type TEXT NOT NULL, entity_id TEXT, request_id TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_stock_fifo ON stock_batches(status,created_at,id) WHERE remaining_grams>0;
CREATE INDEX idx_sales_customer_id ON sales(customer_id); CREATE INDEX idx_sales_created_at ON sales(created_at DESC);
CREATE INDEX idx_sba_sale_id ON sale_batch_assignments(sale_id); CREATE INDEX idx_sba_batch_id ON sale_batch_assignments(batch_id);
CREATE INDEX idx_payments_customer_id ON payments(customer_id); CREATE INDEX idx_journal_reference ON journal_entries(reference_type,reference_id);
CREATE INDEX idx_journal_created_by ON journal_entries(created_by); CREATE INDEX idx_journal_lines_account ON journal_lines(account_id);
CREATE INDEX idx_audit_created_at ON audit_logs(created_at DESC); CREATE INDEX idx_audit_user ON audit_logs(user_id); CREATE INDEX idx_audit_entity ON audit_logs(entity_type,entity_id);
INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
