CREATE TABLE businesses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (btrim(name) <> ''),
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  setup_complete BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The existing installation becomes the first workspace. Existing records keep
-- their IDs; the owner sets new pricing during setup.
INSERT INTO businesses(id, name, slug) VALUES (1, 'My business', 'business-1');
SELECT setval(pg_get_serial_sequence('businesses', 'id'), 1, true);

ALTER TABLE user_roles ADD COLUMN business_id BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id);
ALTER TABLE user_roles ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE user_roles ur SET is_active=u.is_active FROM users u WHERE u.id=ur.user_id;
ALTER TABLE user_roles DROP CONSTRAINT user_roles_pkey;
ALTER TABLE user_roles ADD PRIMARY KEY (business_id, user_id, role_id);

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'customers', 'stock_batches', 'sales', 'sale_batch_assignments',
    'payments', 'settings', 'accounts', 'journal_entries', 'journal_lines', 'audit_logs'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN business_id BIGINT NOT NULL DEFAULT 1 REFERENCES businesses(id)', table_name);
    EXECUTE format(
      'ALTER TABLE %I ALTER COLUMN business_id SET DEFAULT COALESCE(NULLIF(current_setting(''app.business_id'', true), '''')::bigint, 1)',
      table_name
    );
    EXECUTE format('DROP POLICY gramflow_app_server_access ON %I', table_name);
    EXECUTE format(
      'CREATE POLICY gramflow_business_access ON %I FOR ALL TO PUBLIC USING (current_user = ''gramflow_app'' AND business_id = COALESCE(NULLIF(current_setting(''app.business_id'', true), '''')::bigint, 1)) WITH CHECK (current_user = ''gramflow_app'' AND business_id = COALESCE(NULLIF(current_setting(''app.business_id'', true), '''')::bigint, 1))',
      table_name
    );
  END LOOP;
END $$;

ALTER TABLE settings DROP CONSTRAINT settings_pkey;
ALTER TABLE settings ADD PRIMARY KEY (business_id);
ALTER TABLE settings ALTER COLUMN rate_per_gram SET DEFAULT 0;
ALTER TABLE settings ALTER COLUMN special_025_030 SET DEFAULT 0;
ALTER TABLE settings ALTER COLUMN special_050_060 SET DEFAULT 0;
UPDATE settings SET rate_per_gram=0, special_025_030=0, special_050_060=0, updated_at=now();

ALTER TABLE accounts DROP CONSTRAINT accounts_account_code_key;
ALTER TABLE accounts DROP CONSTRAINT accounts_account_name_key;
ALTER TABLE accounts ADD CONSTRAINT accounts_business_code_key UNIQUE (business_id, account_code);
ALTER TABLE accounts ADD CONSTRAINT accounts_business_name_key UNIQUE (business_id, account_name);

CREATE TABLE rate_ranges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL DEFAULT COALESCE(NULLIF(current_setting('app.business_id', true), '')::bigint, 1) REFERENCES businesses(id),
  min_grams NUMERIC(14,3) NOT NULL CHECK (min_grams > 0),
  max_grams NUMERIC(14,3) NOT NULL CHECK (max_grams >= min_grams),
  amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
  UNIQUE (business_id, min_grams, max_grams)
);
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
CREATE POLICY gramflow_app_server_access ON businesses FOR ALL TO PUBLIC
  USING (current_user = 'gramflow_app') WITH CHECK (current_user = 'gramflow_app');
ALTER TABLE rate_ranges ENABLE ROW LEVEL SECURITY;
CREATE POLICY gramflow_business_access ON rate_ranges FOR ALL TO PUBLIC
  USING (current_user = 'gramflow_app' AND business_id = NULLIF(current_setting('app.business_id', true), '')::bigint)
  WITH CHECK (current_user = 'gramflow_app' AND business_id = NULLIF(current_setting('app.business_id', true), '')::bigint);

-- A parent from another business may never satisfy a child reference, even
-- if a caller happens to know its numeric ID.
ALTER TABLE customers ADD CONSTRAINT customers_id_business_key UNIQUE (id, business_id);
ALTER TABLE stock_batches ADD CONSTRAINT stock_batches_id_business_key UNIQUE (id, business_id);
ALTER TABLE sales ADD CONSTRAINT sales_id_business_key UNIQUE (id, business_id);
ALTER TABLE accounts ADD CONSTRAINT accounts_id_business_key UNIQUE (id, business_id);
ALTER TABLE journal_entries ADD CONSTRAINT journal_entries_id_business_key UNIQUE (id, business_id);
ALTER TABLE sales ADD CONSTRAINT sales_customer_business_fk FOREIGN KEY (customer_id, business_id) REFERENCES customers(id, business_id);
ALTER TABLE sale_batch_assignments ADD CONSTRAINT assignments_sale_business_fk FOREIGN KEY (sale_id, business_id) REFERENCES sales(id, business_id);
ALTER TABLE sale_batch_assignments ADD CONSTRAINT assignments_batch_business_fk FOREIGN KEY (batch_id, business_id) REFERENCES stock_batches(id, business_id);
ALTER TABLE payments ADD CONSTRAINT payments_customer_business_fk FOREIGN KEY (customer_id, business_id) REFERENCES customers(id, business_id);
ALTER TABLE accounts ADD CONSTRAINT accounts_parent_business_fk FOREIGN KEY (parent_account_id, business_id) REFERENCES accounts(id, business_id);
ALTER TABLE journal_entries ADD CONSTRAINT journal_reversal_business_fk FOREIGN KEY (reversal_of_id, business_id) REFERENCES journal_entries(id, business_id);
ALTER TABLE journal_lines ADD CONSTRAINT lines_entry_business_fk FOREIGN KEY (journal_entry_id, business_id) REFERENCES journal_entries(id, business_id);
ALTER TABLE journal_lines ADD CONSTRAINT lines_account_business_fk FOREIGN KEY (account_id, business_id) REFERENCES accounts(id, business_id);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gramflow_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON businesses, rate_ranges TO gramflow_app;
    GRANT USAGE, SELECT ON SEQUENCE businesses_id_seq, rate_ranges_id_seq TO gramflow_app;
  END IF;
END $$;
